name: thetiptop_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.1
  shared_preferences: ^2.2.2
  dio: ^5.4.3+1

  # Riverpod
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # UX-UI
  flutter_svg: ^2.0.10+1
  rive: ^0.13.1
  flutter_screenutil: ^5.9.0

  # Data immutable
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  responsive_framework: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

 # Data immutable
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # Riverpod
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/images/
    - assets/audio/music/
    - assets/audio/sfx/


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
    - family: Raleway-SemiBold
      fonts:
        - asset: assets/fonts/Raleway-SemiBold.ttf
    - family: Raleway-Bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf